### ISSUE TITLE
slow info issue

### ISSUE THREAD

**Issue by pedrobibi** [jrunestone/ExtPlaneNet#1]
Hi there,

So, I have a issue with the info coming from Xplane using your interface.

The info comes so slow, in fact comes in "steps" and I don't know why.

I've tested the info with the Dataref tool and the info is really smooth, but with your interface no. I've tested changing the accuracy but no result...

What I'm doing wrong?

This is the code I'm using:

            var iface = new ExtPlaneInterface();
            iface.Connect();

            iface.Subscribe<float[]>("sim/flightmodel/engine/ENGN_ITT_c", 0, (engITT) =>
            {
                eng1ITT = engITT.Value[0];
                eng2ITT = engITT.Value[1];
            });

**Comment by jrunestone** [comment]
Hi!

Can you elaborate a bit on the "stepping"? I.e. in which intervals does the data come in compared to the dataref tool? Is it every second or every 30 milliseconds or what?

This API relies on an underlying plugin (ExtPlane) via TCP network which really isn't designed for absolute realtime updates as far as I know, but it should be close. I haven't used this code in a while but I could give it a try in the next couple of days.

Have you tried setting the accuracy to something other than 0? Like 0.0001. Can you test the underlying plugin directly as described here? https://github.com/vranki/ExtPlane#test-session

For debugging purposes you could also try managing your own thread/task and polling the dataref value directly:

```
iface.Subscribe<float[]>("sim/flightmodel/engine/ENGN_ITT_c")
DataRef<float[]> dataRef = iface.GetDataRef<float[]>("sim/flightmodel/engine/ENGN_ITT_c");

(in your thread):
dataRef.Value
```

**Comment by pedrobibi** [comment]
Hi,

first of all thanks a lot for your quick answer, I'm really greatful...

Ok, "stepping", well, the ITT temperature starts in my plane usually in around 618 and the next step is  around 630, 645, etc... probably the steps are around 15 or 16 celsius degrees. In miliseconds? I don't know, but I assure you that the info is clearly visible, then the time is enough to see the numbers passing :-)

In the Dataref tool, the info, comes in really little steps, as decimals, the "feeling" is a smooth progress, do you know what I mean?

I have tried the minimum accuracy as 0.000001f and nothing better happens.

I'll proceed to test via TELNET this evening maybe and also the debugging process, but I must say that I'm really newbie programming in any language, not only in c# :-)

Again, thank you and have a nice day.

Regards

**Comment by jrunestone** [comment]
So it's not the update rate that's slow, but rather the values that are coming in are in higher steps than what you're getting in the dataref tool for example?

I don't even have X-Plane installed but I'll see if I can make time to try it out myself :P
