### ISSUE TITLE
Float and double values not converted correctly

### ISSUE THREAD

**Issue by SamuelReithmeir** [jrunestone/ExtPlaneNet#2]
On Windows Culture settings that use "," as comma seperator e.g. german double and float values are not converted correctly. E.g.: 23.3 => 233

**Comment by jrunestone** [comment]
Do you mean that the values coming in are "23,3" or in fact "23.3"?

**Comment by SamuelReithmeir** [comment]
Extplane sends the data as "ud 23.3\n"  when you call iface.get it returns 233 because it thinks the "." is just a thousand notator. We germans sometimes write one million as 1.000.000, and windows system.convert uses the local culture to convert numbers.

**Comment by jrunestone** [comment]
Thanks that explains it. Should be using invariant culture for the conversion I guess, I'll take a look.

**Comment by jrunestone** [comment]
Check out the new dll here https://github.com/jrunestone/ExtPlaneNet/tree/develop/build or use the develop branch if you're using the code and let me know if that solves the issue.

**Comment by SamuelReithmeir** [comment]
yeah, now it works as intended

**Comment by SamuelReithmeir** [comment]
but setting the values doesn't

**Comment by jrunestone** [comment]
Just decimal values or any kind of value? Did that work before?

**Comment by SamuelReithmeir** [comment]
i am setting 7 double and float values in my project, it works when using it on a windows system with english language settings, but on my german laptop when i set float and double values nothing happens.

**Comment by jrunestone** [comment]
I can't debug this code but I think I found the place where the value is being set and fixed it there too. Please check. Also, do you know if this is an issue when setting an array of values as well?

**Comment by SamuelReithmeir** [comment]
Okay, setting datarefs now works as expected, so does setting array values.

**Comment by jrunestone** [comment]
Ok thanks for your help, i'll merge it to master.

**Comment by SamuelReithmeir** [comment]
Happy to help, thanks for the fast response.
